

agent:
  serverUrl: https://192.168.0.170:50401
  name: 测试001
  port: 5656
  token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJnZW5kZXIiOiIwIiwiYWNjb3VudE5hbWUiOiJhZG1pbiIsImF2YXRhciI6Ii9lbGNvLW9zcy9taW5pby9lbGNvLWh1YXJ1aS1vc3MtbWluaW8vMjAyMi8wNy8wMS8tIOWJr-acrC0tMGM3NDA0NTEyMWU5NDFhY2EyM2Y2YzVjZjlhNWJmZDUucG5nIiwicGtVc2VyIjoiMTQ2MzQzNTc3NzYzNDU5ODkxMiIsInVzZXJOYW1lIjoi6LaF57qn566h55CG5ZGYIiwibmJmIjoxNjcwNTUyMTUwLCJwaG9uZSI6IjEzNjYyMDIwMDMwIiwidGVuYW50SWQiOiIxNDc4OTYzNzk0NjI0NTEyMDAwIiwiZXhwIjoxNjczMjMwNTUwLCJpYXQiOjE2NzA1NTIxNTAsImVtYWlsIjoiMkBxcS5jb20iLCJqdGkiOiJkMjk5MmYyMy1iZmIwLTRkZjYtYjUxMi1lZmJhNmMwZTcwZDIifQ.uQVT-xW-J8PuLbSLr06N3a-V8-DMylHThnEMLP9hH2M
  baseFolder: ./elco/agentsdk
